timeout: 500

http:
  rootPath: /dynaship/*
  port: 8080
  adminPort: 8081
  requestLog:
    console:
      enabled: false
    file:
      enabled: false
    syslog:
      enabled: false

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ERROR
  loggers:
    "se.dynabyte": ERROR
    "se.dynabyte.dynaship.service.getmove.resource": ERROR
    "se.dynabyte.dynaship.service.getmove.util.advanced.GameStateLogger": DEBUG
    "se.dynabyte.dynaship.service.getmove.ai.advanced.TimedGameStateEvaluator": DEBUG
    "se.dynabyte.dynaship.service.getmove.ai.advanced.ChainGameStateEvaluationStrategy": ERROR
    "se.dynabyte.dynaship.service.getmove.ai.advanced.SimpleGameStateEvaluationStrategy": ERROR
    "se.dynabyte.dynaship.service.getmove.ai.advanced.existinghit.ExistingHitGameStateEvaluationStrategy": ERROR
    "se.dynabyte.dynaship.service.getmove.ai.advanced.probabilitydensity.ProbabilityDensityGameStateEvaluationStrategy": DEBUG
    "org.eclipse.jetty": ERROR
    "com.github": ERROR
    "com.yammer.dropwizard": INFO
    "com.yammer.dropwizard.config.ServerFactory": ERROR
  console:
    enabled: true
